# Generated by Django 2.0.1 on 2018-01-15 09:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.TextField(verbose_name='信息')),
                ('author', models.CharField(default='', max_length=20, verbose_name='来源')),
                ('infotime', models.DateTimeField(default=datetime.datetime(2018, 1, 15, 17, 17, 31, 849767), verbose_name='加入时间')),
                ('infoid', models.CharField(max_length=20, verbose_name='信息ID')),
            ],
        ),
    ]
