# Generated by Django 2.0.1 on 2018-01-15 09:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0002_auto_20180115_1736'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='information',
            options={'verbose_name': '信息流', 'verbose_name_plural': '信息流'},
        ),
        migrations.AlterField(
            model_name='information',
            name='infotime',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 15, 17, 43, 17, 701983), verbose_name='加入时间'),
        ),
    ]
