# Generated by Django 2.0.1 on 2018-01-16 08:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0003_auto_20180115_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='disfavor',
            field=models.IntegerField(default=0, verbose_name='不赞成'),
        ),
        migrations.AddField(
            model_name='information',
            name='favour',
            field=models.IntegerField(default=0, verbose_name='赞成'),
        ),
        migrations.AlterField(
            model_name='information',
            name='infotime',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 16, 16, 40, 40, 545652), verbose_name='加入时间'),
        ),
    ]
