# Generated by Django 2.0.1 on 2018-01-16 09:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0004_auto_20180116_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='crawltime',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 16, 17, 34, 20, 272491), verbose_name='爬取时间'),
        ),
        migrations.AlterField(
            model_name='information',
            name='infotime',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 16, 17, 34, 20, 272465), verbose_name='加入时间'),
        ),
    ]
