# Generated by Django 2.0.1 on 2018-01-17 10:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0005_auto_20180116_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='author',
            field=models.URLField(default='', max_length=50, verbose_name='来源'),
        ),
        migrations.AlterField(
            model_name='information',
            name='crawltime',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 17, 10, 33, 13, 565036), verbose_name='爬取时间'),
        ),
        migrations.AlterField(
            model_name='information',
            name='infotime',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 17, 10, 33, 13, 565010), verbose_name='加入时间'),
        ),
    ]
