# Generated by Django 2.0.1 on 2018-01-17 10:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0006_auto_20180117_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='crawltime',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='爬取时间'),
        ),
        migrations.AlterField(
            model_name='information',
            name='infotime',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='加入时间'),
        ),
    ]
